### ISSUE TITLE
shell executor

### ISSUE THREAD

**Issue by venerice** [krpn/prometheus-alert-webhooker#19]
I keep getting the same error "no such file or directory" in shell executor. I  made sure that shell script mount in docker. My config 
  - executor: shell
    parameters:
      command: /clean.sh ${LABEL_ALERTNAME}
    block: 30m
Docker logs
{"alert":"monitoring_exchange_order","context":"runner","details":{"command":"/clean.sh monitoring_exchange_order"},"duration":"12.734618ms","event_id":"a238","executor":"shell","level":"error","msg":"runner got executing task #1/1 error, stopping group: fork/exec /clean.sh monitoring_exchange_order: no such file or directory","result":"exec_error","rule":"JenkinsAutofix","tasks":[{"alert":"monitoring_exchange_order","details":{"command":"/clean.sh monitoring_exchange_order"},"event_id":"a238","executor":"shell","rule":"JenkinsAutofix"}]

When connect to container script already in /clean.sh
Tell me why this is happening?

**Comment by krpn** [comment]
@venerice, try to use absolute path to script. There is mistake in relative path possible.

**Comment by JBaptisme33** [comment]
Hi,
Thanks for work.

I'm facing same issue regarding path.

I've tried all possible way to lauch something:
```
bash scripts/rolling-replace.sh
scripts/rolling-replace.sh
./scripts/rolling-replace.sh
/scripts/rolling-replace.sh
scripts/..data/rolling-replace.sh (since there is a symlink)

```
{"alert":"NFSClientMountIssue","context":"runner","details":{"command":"scripts/..data/rolling-replace.sh  xxxxxxxx"},"duration":"461.859µs","event_id":"c7f9","executor":"shell","level":"error","msg":"runner got executing task #1/1 error, stopping group: fork/exec scripts/..data/rolling-replace.sh  xxxxxxxx: no such file or directory","result":"exec_error","rule":"rolling-replace","tasks":[{"alert":"NFSClientMountIssue","details":{"command":"scripts/..data/rolling-replace.sh xxxxxxxx"},"event_id":"c7f9","executor":"shell","rule":"rolling-replace"}],"time":"2022-05-05T15:34:54Z"}


Whereas, lauch from bash is working:

```
root@xxxxxx:/# scripts/..data/rolling-replace.sh 
````

Persmissions seem good: (exec for all)

```
:/# ls -alh scripts/
total 12K
drwxrwxrwx 3 root root 4.0K May  5 15:39 .
drwxr-xr-x 1 root root 4.0K May  5 15:39 ..
drwxr-xr-x 2 root root 4.0K May  5 15:39 ..2022_05_05_15_39_46.540880911
lrwxrwxrwx 1 root root   31 May  5 15:39 ..data -> ..2022_05_05_15_39_46.540880911
lrwxrwxrwx 1 root root   25 May  5 15:39 rolling-replace.sh -> ..data/rolling-replace.sh


Do you have an idea @krpn ?

**Comment by JBaptisme33** [comment]
@krpn

**Comment by krpn** [comment]
@JBaptisme33, try to change command to `bash /scripts/rolling-replace.sh`.
