### ISSUE TITLE
On low disk space trigger Jenkins job

### ISSUE THREAD

**Issue by pujamudaliar** [krpn/prometheus-alert-webhooker#20]
Hello Team,

How can I trigger a jenkins job on low disk space or when a container is down. 
Jenkins job does not trigger with the following configuration, but my requirement is to trigger job on low disk space.

block_cache_size: 52428800

pool_size: 100

runners: 10

remote_config_refresh_interval: 60s

common_parameters:
  jenkins_credentials:
    endpoint: http://hostname:8080
    login: admin
    password: <password>
    state_refresh_delay: 5s

rules:
- name: JenkinsAutofix
  conditions:
    labels:
      webhooker_jenkins_autofix: enable
      jenkins_job: (.*?)
      intent: jenkins-webhook

  actions:
  - executor: jenkins
    common_parameters: jenkins_credentials
    parameters:
      job: test-job

**Comment by krpn** [comment]
@pujamudaliar,

1. Check your alerts:
    - Low disk space
    - Container is down
2. Check your Jenkins credentials in webhooker configuration.
