### ISSUE TITLE
All http requests return HTTP status: 400, body close error: \u003cnil\u003e

### ISSUE THREAD

**Issue by kenjc55** [krpn/prometheus-alert-webhooker#21]
Why do all of my http requests return HTTP status: 400, body close error: \u003cnil\u003e?

block_cache_size: 52428800

pool_size: 100

runners: 10

remote_config_refresh_interval: 60s

rules:
- name: all-alerts
  conditions:
    alert_status: firing
  actions:
  - executor: http
    parameters:
      url: http://apprise-api.dev.cloud.xxx.xxx/notify/ssi-systems 
      method: POST
      header Content-Type: application/json
      body: '{"tag": "okd4","body": "test"}'

I use the following curl command to test the url:

curl -X POST -d '{"tag":"okd4", "body":"test message"}' -H "Content-Type: application/json" http://apprise-api.dev.cloud.xxx.xxx/notify/ssi-systems

**Comment by krpn** [comment]
@kenjc55, your configuration seems to be correct. Did you solve your problem?

1. Check logs. They provide details about HTTP request
2. Check request body in your configuration: there is possibility to make error in quotes
