### ISSUE TITLE
Debugging example

### ISSUE THREAD

**Issue by Spritekin** [krpn/prometheus-alert-webhooker#22]
Would you please add how to debug this service?
Just a simple curl command that can be executed to simulate a message from alertmanager including one alert with simple labels and annotations?

**Comment by Spritekin** [comment]
i.e. something like

curl -X POST http://10.103.110.154:9093/webhooker -d '[{"status": "firing", "labels": {"alertname": "my-alert", "service": "my-service", "severity":"critical"}, "annotations": {"summary": "Some problem"},"generatorURL": "http://prometheus.int.example.net/<generating_expression>"}]'

**Comment by krpn** [comment]
@Spritekin, you can find body example in tests: https://github.com/krpn/prometheus-alert-webhooker/blob/master/webhook/webhook_test.go#L64

**Comment by Spritekin** [comment]
Do you mind if I submit a PR with some code examples for testing or debugging purposes?

In my case, I have installed this in kubernetes with a "shell" rule that should echo "hello world". Then I'm trying to have alertmanager to post an alert but nothing happens. So I would like to simulate the post event to find out if the problem is AM or my webhooker setup.

I guess other people might have similar problems so this kind of examples might be useful.

Regards,

**Comment by krpn** [comment]
@Spritekin, yes, of course. You may add it to README.md.

**Comment by Spritekin** [comment]
Done, its in a PR.

**Comment by Spritekin** [comment]
Also, I'm working on a simple trello integration, once done I might add another entry to the readme.
