### ISSUE TITLE
Output of the commands?

### ISSUE THREAD

**Issue by Spritekin** [krpn/prometheus-alert-webhooker#24]
I'm trying to run some shell commands and I can see the webhooker logs saying there is an error in my command, but I would really like to see the echo of my commands.

Is there a way to enable the console output so I can see the stderr/stdout of the shell commands?

**Comment by krpn** [comment]
~~@Spritekin, unfortunately, there isn't now. I am able to add extra logging next week (after vocation).~~

**Comment by krpn** [comment]
Checked the source code attentively. @Spritekin, you should see error details in logs. Such as `runner got executing task #1/1 error, stopping group: <ERROR FROM stderr HERE>`. Could you please show me your log?
